#!/usr/bin/env bash

# Validate commit subjects against the convention in AGENTS.md.
#
#   tests/commit-message.sh                 check commits not yet on origin/main
#   tests/commit-message.sh RANGE           check a git range, e.g. main..HEAD
#   tests/commit-message.sh --text "..."    check one subject, for a title or a hook
#
# Deliberately not commitlint. Everything checked here is prefix matching, a
# length comparison, and a trailing-character test, which is what this
# repository is already made of. Keeping it in shell means a contributor can run
# it before pushing instead of learning the rules from a rejected pull request.

set -euo pipefail

TYPES="fix|feat|docs|ci|test|refactor|chore|perf|build|style|revert"
SUBJECT_SOFT=50
SUBJECT_HARD=72

failures=0

fail() {
    printf 'invalid: %s\n  %s\n' "$1" "$2" >&2
    failures=$((failures + 1))
}

# Checks one subject line. The rules mirror AGENTS.md; anything not checkable
# here, such as imperative mood, stays a convention rather than a check.
check_subject() {
    local subject="$1" type_part

    [ -n "$subject" ] || return 0

    # Merge commits are generated by GitHub and are not authored messages.
    case "$subject" in
        "Merge "*) return 0 ;;
    esac

    if ! printf '%s' "$subject" | grep -qE "^($TYPES)(\([a-z0-9./-]+\))?!?: .+"; then
        fail "$subject" "expected '<type>(<scope>): <summary>' with type one of: ${TYPES//|/, }"
        return 0
    fi

    if [ "${#subject}" -gt "$SUBJECT_HARD" ]; then
        fail "$subject" "subject is ${#subject} characters, hard limit is $SUBJECT_HARD"
    elif [ "${#subject}" -gt "$SUBJECT_SOFT" ]; then
        printf 'warning: subject is %s characters, aim for %s\n  %s\n' \
            "${#subject}" "$SUBJECT_SOFT" "$subject" >&2
    fi

    case "$subject" in
        *.) fail "$subject" "subject must not end with a period" ;;
    esac

    # Lowercase after the colon: a capital usually means a sentence was pasted in.
    type_part="${subject#*: }"
    case "$type_part" in
        [A-Z]*) fail "$subject" "summary should not start with a capital letter" ;;
    esac
}

main() {
    local range subject

    if [ "${1:-}" = "--text" ]; then
        check_subject "${2:-}"
        [ "$failures" -eq 0 ] || exit 1
        echo "Commit message is valid."
        return
    fi

    if [ "$#" -gt 0 ]; then
        range="$1"
    elif git rev-parse --verify --quiet origin/main >/dev/null; then
        range="origin/main..HEAD"
    else
        range="HEAD~1..HEAD"
    fi

    if [ -z "$(git rev-list "$range" 2>/dev/null)" ]; then
        echo "No commits in $range to check."
        return
    fi

    while IFS= read -r subject; do
        [ -n "$subject" ] || continue
        check_subject "$subject"
    done <<EOF
$(git log --format=%s "$range")
EOF

    [ "$failures" -eq 0 ] || exit 1
    echo "Commit messages in $range are valid."
}

main "$@"
